"""
Offline-First Sync Router for SIH26002 - NER Smart Logistics Platform.

Allows field drivers and vendors to batch-upload vehicle_location and incident
records that were collected while offline. Each record carries a unique
client_record_id to prevent duplicate submissions on retry.
"""
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import List, Optional
from fastapi import APIRouter, Depends, status
from pydantic import BaseModel, Field
from sqlalchemy.orm import Session

root_dir = Path(__file__).resolve().parent.parent
if str(root_dir) not in sys.path:
    sys.path.insert(0, str(root_dir))

try:
    from backend.database import get_db
    from backend import models
except ModuleNotFoundError:
    from database import get_db
    import models


router = APIRouter(tags=["Offline Sync"])


# ----------------------------------------------------
# Helper: parse ISO timestamp safely
# ----------------------------------------------------
def _parse_timestamp(val: Optional[str]) -> datetime:
    if not val:
        return datetime.now(timezone.utc)
    try:
        return datetime.fromisoformat(val.replace("Z", "+00:00"))
    except Exception:
        return datetime.now(timezone.utc)


# ----------------------------------------------------
# Pydantic Schemas
# ----------------------------------------------------
class SyncRecord(BaseModel):
    """A single offline-collected record to synchronize."""
    client_record_id: str = Field(
        ...,
        min_length=1,
        description="Unique ID generated by the client app to prevent duplicate sync",
        example="loc-V001-20260916-103000"
    )
    record_type: str = Field(
        ...,
        description="Type of record: 'vehicle_location' or 'incident'",
        example="vehicle_location"
    )
    vehicle_id: str = Field(..., min_length=1, example="V001")
    latitude: float = Field(..., ge=-90.0, le=90.0, example=24.817)
    longitude: float = Field(..., ge=-180.0, le=180.0, example=93.936)
    timestamp: Optional[str] = Field(None, example="2026-09-16T10:30:00")

    # Incident-specific fields (required only when record_type == "incident")
    incident_type: Optional[str] = Field(None, example="LANDSLIDE")
    description: Optional[str] = Field(None, example="Road blockage")

    model_config = {
        "json_schema_extra": {
            "examples": [
                {
                    "client_record_id": "loc-V001-20260916-103000",
                    "record_type": "vehicle_location",
                    "vehicle_id": "V001",
                    "latitude": 24.817,
                    "longitude": 93.936,
                    "timestamp": "2026-09-16T10:30:00"
                },
                {
                    "client_record_id": "inc-V001-20260916-103200",
                    "record_type": "incident",
                    "vehicle_id": "V001",
                    "latitude": 24.817,
                    "longitude": 93.936,
                    "incident_type": "LANDSLIDE",
                    "description": "Road blockage",
                    "timestamp": "2026-09-16T10:32:00"
                }
            ]
        }
    }


class SyncRequest(BaseModel):
    """Batch of offline records to synchronize."""
    records: List[SyncRecord] = Field(
        ...,
        min_length=1,
        description="List of offline-collected records to sync"
    )

    model_config = {
        "json_schema_extra": {
            "example": {
                "records": [
                    {
                        "client_record_id": "loc-V001-20260916-103000",
                        "record_type": "vehicle_location",
                        "vehicle_id": "V001",
                        "latitude": 24.817,
                        "longitude": 93.936,
                        "timestamp": "2026-09-16T10:30:00"
                    },
                    {
                        "client_record_id": "inc-V001-20260916-103200",
                        "record_type": "incident",
                        "vehicle_id": "V001",
                        "latitude": 24.817,
                        "longitude": 93.936,
                        "incident_type": "LANDSLIDE",
                        "description": "Road blockage",
                        "timestamp": "2026-09-16T10:32:00"
                    }
                ]
            }
        }
    }


class SyncResultItem(BaseModel):
    client_record_id: str
    status: str  # "synced", "duplicate", or "failed"
    detail: str


class SyncResponse(BaseModel):
    total_received: int
    synced: int
    duplicates: int
    failed: int
    results: List[SyncResultItem]


# ----------------------------------------------------
# Helper: ensure vehicle exists in the vehicles table
# ----------------------------------------------------
def _ensure_vehicle(db: Session, vehicle_id: str):
    vehicle = db.query(models.Vehicle).filter(
        models.Vehicle.vehicle_id == vehicle_id
    ).first()
    if not vehicle:
        vehicle = models.Vehicle(vehicle_id=vehicle_id)
        db.add(vehicle)
        db.commit()
        db.refresh(vehicle)
    return vehicle


# ----------------------------------------------------
# Sync processing logic
# ----------------------------------------------------
def _process_vehicle_location(record: SyncRecord, db: Session) -> SyncResultItem:
    """Process a single vehicle_location sync record."""
    # Check for duplicate using client_record_id
    existing = db.query(models.VehicleLocation).filter(
        models.VehicleLocation.client_record_id == record.client_record_id
    ).first()
    if existing:
        return SyncResultItem(
            client_record_id=record.client_record_id,
            status="duplicate",
            detail="Record already synced previously"
        )

    _ensure_vehicle(db, record.vehicle_id)

    db_location = models.VehicleLocation(
        vehicle_id=record.vehicle_id,
        latitude=record.latitude,
        longitude=record.longitude,
        timestamp=_parse_timestamp(record.timestamp),
        client_record_id=record.client_record_id
    )
    db.add(db_location)
    db.commit()
    return SyncResultItem(
        client_record_id=record.client_record_id,
        status="synced",
        detail="Vehicle location saved to database"
    )


def _process_incident(record: SyncRecord, db: Session) -> SyncResultItem:
    """Process a single incident sync record."""
    # Validate incident-specific fields
    if not record.incident_type:
        return SyncResultItem(
            client_record_id=record.client_record_id,
            status="failed",
            detail="Missing required field: incident_type"
        )
    if not record.description:
        return SyncResultItem(
            client_record_id=record.client_record_id,
            status="failed",
            detail="Missing required field: description"
        )

    # Check for duplicate
    existing = db.query(models.Incident).filter(
        models.Incident.client_record_id == record.client_record_id
    ).first()
    if existing:
        return SyncResultItem(
            client_record_id=record.client_record_id,
            status="duplicate",
            detail="Record already synced previously"
        )

    db_incident = models.Incident(
        vehicle_id=record.vehicle_id,
        latitude=record.latitude,
        longitude=record.longitude,
        incident_type=record.incident_type,
        description=record.description,
        timestamp=_parse_timestamp(record.timestamp),
        client_record_id=record.client_record_id
    )
    db.add(db_incident)
    db.commit()
    return SyncResultItem(
        client_record_id=record.client_record_id,
        status="synced",
        detail="Incident saved to database"
    )


# ----------------------------------------------------
# POST /api/sync endpoint
# ----------------------------------------------------
@router.post("/api/sync", response_model=SyncResponse, status_code=status.HTTP_200_OK)
def sync_offline_records(request: SyncRequest, db: Session = Depends(get_db)):
    """
    Batch-synchronize offline-collected vehicle locations and incident reports.
    Each record's client_record_id prevents duplicate submissions on retry.
    """
    results: List[SyncResultItem] = []

    for record in request.records:
        try:
            if record.record_type == "vehicle_location":
                result = _process_vehicle_location(record, db)
            elif record.record_type == "incident":
                result = _process_incident(record, db)
            else:
                result = SyncResultItem(
                    client_record_id=record.client_record_id,
                    status="failed",
                    detail=f"Unknown record_type: '{record.record_type}'. Must be 'vehicle_location' or 'incident'"
                )
        except Exception as e:
            db.rollback()
            result = SyncResultItem(
                client_record_id=record.client_record_id,
                status="failed",
                detail=f"Server error: {str(e)}"
            )
        results.append(result)

    synced_count = sum(1 for r in results if r.status == "synced")
    duplicate_count = sum(1 for r in results if r.status == "duplicate")
    failed_count = sum(1 for r in results if r.status == "failed")

    return SyncResponse(
        total_received=len(results),
        synced=synced_count,
        duplicates=duplicate_count,
        failed=failed_count,
        results=results
    )
